# Generated by Django 3.0.8 on 2020-10-07 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('IT_ID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('IT_PRECIO', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('PED_ID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('PED_CANTIDAD', models.IntegerField()),
                ('CLIE_CEDULA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Levip.Cliente')),
                ('PED_IT', models.ManyToManyField(to='Levip.Item')),
            ],
        ),
    ]
