# Generated by Django 3.0.8 on 2020-09-28 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('CLIE_CEDULA', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('CLIE_NOMBRE', models.CharField(max_length=50)),
                ('CLIE_RUC', models.CharField(blank=True, max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Despachador',
            fields=[
                ('DES_ID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('DES_NOMBRE', models.CharField(max_length=25)),
                ('DES_APELLIDO', models.CharField(max_length=25)),
                ('DES_TELEFONO', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('IT_ID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('IT_MEDIDA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IT_DESCRIPCION', models.TextField()),
                ('DES_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Levip.Despachador')),
            ],
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('PRE_ID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('PRE_FECHA_INICIO', models.DateField()),
                ('PRE_FECHA_FINAL', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('PED_ID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('PED_CANTIDAD', models.IntegerField()),
                ('CLIE_CEDULA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Levip.Cliente')),
                ('IT_ID', models.ManyToManyField(to='Levip.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('ORD_ID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('ORD_ENCABEZADO', models.TextField()),
                ('DES_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Levip.Despachador')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='ORD_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Levip.Orden'),
        ),
        migrations.AddField(
            model_name='item',
            name='PRE_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Levip.Precio'),
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('DIR_CODIGO', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('DIR_TIPO', models.CharField(max_length=100)),
                ('CLIE_CEDULA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Levip.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('ADMIN_ID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('ADMIN_USUARIO', models.CharField(max_length=50)),
                ('ADMIN_CONTRASENA', models.TextField()),
                ('CLIE_CEDULA', models.ManyToManyField(to='Levip.Cliente')),
                ('IT_CODIGO', models.ManyToManyField(to='Levip.Item')),
            ],
        ),
    ]
