# Generated by Django 3.0.8 on 2020-10-07 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Levip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='PED_IT',
        ),
        migrations.AddField(
            model_name='pedido',
            name='IT_ID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Levip.Item'),
        ),
    ]
