# Generated by Django 3.0.8 on 2020-10-05 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Levip', '0001_initial'),
    ]

    operations = [
    ]
