# Generated by Django 3.0.8 on 2020-10-06 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Levip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='CLIE_CEDULA',
        ),
        migrations.RemoveField(
            model_name='item',
            name='DES_ID',
        ),
        migrations.RemoveField(
            model_name='item',
            name='ORD_ID',
        ),
        migrations.RemoveField(
            model_name='item',
            name='PRE_ID',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='DES_ID',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='IT_ID',
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.DeleteModel(
            name='Despachador',
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
        migrations.DeleteModel(
            name='Precio',
        ),
    ]
