# Generated by Django 3.0.8 on 2020-10-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Levip', '0002_auto_20201004_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='ADMIN_CONTRASENA',
        ),
        migrations.AddField(
            model_name='administrador',
            name='ADMIN_CORREO',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='CLIE_CORREO',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='despachador',
            name='DES_CORREO',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='precio',
            name='PRE_VALOR',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
