# Generated by Django 3.0.8 on 2020-10-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Levip', '0002_auto_20201006_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='IT_ID',
        ),
        migrations.AddField(
            model_name='pedido',
            name='IT_ID',
            field=models.ManyToManyField(default=None, to='Levip.Item'),
        ),
    ]
