# Generated by Django 3.0.8 on 2020-10-05 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Levip', '0003_auto_20201004_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='CLIE_RUC',
        ),
    ]
