# Generated by Django 3.0.8 on 2020-10-07 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Levip', '0003_auto_20201006_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='IT_ID',
        ),
        migrations.AddField(
            model_name='pedido',
            name='IT_ID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Levip.Item'),
        ),
    ]
