# Generated by Django 3.0.8 on 2020-10-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Levip', '0004_remove_cliente_clie_ruc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='ORD_ID',
        ),
        migrations.AddField(
            model_name='orden',
            name='OR_IT',
            field=models.ManyToManyField(to='Levip.Item'),
        ),
    ]
