# Generated by Django 3.0.8 on 2020-10-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Levip', '0004_auto_20201006_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='IT_NOMBRE',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
